dokumentor/urls.py
from django.conf.urls import patterns, url

from dokumentor import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'projects/(\d+)/$', views.view_project, name='view_project'),
        url(r'name_step/$', views.name_step, name='name_step'),
        url(r'name_step/(\d+)/$', views.name_step, name='name_step'),
        url(r'photo_step/(\d+)/$', views.photo_step, name='photo_step'),
        url(r'build_step/(\d+)/$', views.build_step, name='build_step'),
        url(r'better_description/(\d+)/$', views.better_description, name='better_description'),
        )

plan2fab/urls.py
from django.conf import settings

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'', include('dokumentor.urls', namespace="projects")),
    url(r'^dokumentor/', include('dokumentor.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dokumentor/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location='medias')

from taggit.managers import TaggableManager

class Project(models.Model):
    name = models.CharField(max_length=100,unique=True,blank=False)
    description = models.TextField()
    duration = models.PositiveSmallIntegerField(default=0)
    plan = models.FileField()
    furnitures = models.TextField()
    authors = models.TextField()
    history = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    photo = models.ImageField(storage=fs, null=True)

    def __str__(self):
        return self.name

dokumentor/forms.py
from django.forms import ModelForm

from dokumentor.models import Project

class NameStepForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']

class BuildStepForm(ModelForm):
    class Meta:
        model = Project
        fields = ['furnitures', 'duration']

class BetterDescriptionForm(ModelForm):
    class Meta:
        model = Project
        fields = ['history', 'tags']

class PhotoStepForm(ModelForm):
    class Meta:
        model = Project
        fields = ['photo']

dokumentor/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

from dokumentor.models import Project
from dokumentor.forms import (
    NameStepForm,
    BuildStepForm,
    BetterDescriptionForm,
    PhotoStepForm,
)

def index(request):
    projects = Project.objects.order_by('created_at')
    context = { 'projects': projects, }
    return render(request, 'dokumentor/index.html', context)


def name_step(request, id=None):
    try:
        project = Project.objects.get(id=id)
    except ObjectDoesNotExist:
        project = Project()

    if request.method == 'POST':
        form = NameStepForm(request.POST, instance=project)
        new_project = form.save()
        return redirect('projects:index')

    else:
        form = NameStepForm(instance=project)
    return render(request, 'dokumentor/name_step.html', {'form': form})

def build_step(request, id):
    try:
        project = Project.objects.get(id=id)
    except ObjectDoesNotExist:
        return redirect('projects:index')

    if request.method == 'POST':
        BuildStepForm(request.POST, instance=project).save()
        return redirect('projects:index')
    else:
        form = BuildStepForm(instance=project)
        return render(request, 'dokumentor/build_step.html', {'form': form})

def photo_step(request, id):
    project = Project.objects.get(id=id)
    if request.method == 'POST':
        form = PhotoStepForm(request.POST, request.FILES, instance=project)
        new_photo = form.save()
        return redirect('projects:index')
    else:
        form = PhotoStepForm(instance=project)
    return render(request, 'dokumentor/photo_step.html', {'form': form})

def view_project(request, id):
    project = Project.objects.get(id=id)
    return render(request, 'dokumentor/project.html', {'project': project})

def better_description(request, id):
    project = Project.objects.get(id=id)
    if request.method == 'POST':
        form = BetterDescriptionForm(request.POST, instance=project)
        new_tags = form.save()
        return redirect('projects:index')
    else:
        form = BetterDescriptionForm(instance=project)
    return render(request, 'dokumentor/better_description.html', {'form': form})

dokumentor/templates/dokumentor/base_dokumentor.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Plan 2 Fab - Documentation de projet de fabrication</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'dokumentor/style.css' %}" />
  </head>
  <body>
    <header>
      <h1>Plan 2 Fab<h1>
          <img src="{% static 'dokumentor/images/ecodesignfablab.jpg' %}" alt="écodesignfablab"/>
    </header>
    <main>
      {% block content %}{% endblock content %}
    </main>
  </body>
</html>

dokumentor/templates/dokumentor/better_description.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
<p> Better Description </p>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
  <input type="submit" value="Ajouter ces info sur la fabrication"/>
  <a href="{% url 'projects:index' %}">retour</a>
  </p>
</form>
{% endblock content %}

dokumentor/templates/dokumentor/build_step.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
<p> How to build project </p>
<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
  <input type="submit" value="Ajouter ces info sur la fabrication"/>
  <a href="{% url 'projects:index' %}">retour</a>
  </p>
</form>
{% endblock content %}

dokumentor/templates/dokumentor/index.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
{% if projects %}
<ul>
  {% for project in projects %}
  <li><a href="{% url 'projects:view_project' project.id %}" >{{ project.name }}</a> [{{ project.created_at }}]
    <a href="{% url 'projects:build_step' project.id %}">Comment le fabriquer ?</a>
    <a href="{% url 'projects:better_description' project.id %}" >Améliorer la description</a>
    <a href="{% url 'projects:photo_step' project.id %}" >Ajouter des photos</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No Projects are available.</p>
{% endif %}

<a href='{% url 'projects:name_step' %}'>Documenter un projet</a>
{% endblock content %}

dokumentor/templates/dokumentor/name_step.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
<p>Nouveau projet</p>
<form method="post" action="{% url 'projects:name_step' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
  <input type="submit" value="Créer ce projet"/>
  <a href="{% url 'projects:index' %}">Retour au tableau de bord</a>
  </p>
</form>
{% endblock content %}

dokumentor/templates/dokumentor/photo_step.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
<p>Ajouter une photo au projet</p>
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
  <input type="submit" value="Ajouter la photo"/>
  <a href="{% url 'projects:index' %}">Retour au tableau de bord</a>
  </p>
</form>
{% endblock content %}

dokumentor/templates/dokumentor/project.html
{% extends "dokumentor/base_dokumentor.html" %}

{% block content %}
<h1>{{ project.name }}</h1>
<p>{{ project.description }}</p>
<a href="{% url 'projects:name_step' project.id %}">Éditer</a>
<ul>
    Tags :
    {% for tag in project.tags.all %}
    <li>{{tag }}</li>

    {% endfor %}
</ul>

{% endblock content %}